apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
data:
  alerts.yml: |
    groups:
    - name: autohealops-alerts
      rules:
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[1m]) > 0.5
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above threshold for 30 seconds."

      - alert: PodDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Pod is down"
          description: "A Kubernetes pod is not running."
