apiVersion: apps/v1
kind: Deployment
metadata:
  name: autohealops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autohealops
  template:
    metadata:
      labels:
        app: autohealops
    spec:
      containers:
        - name: backend
          image: autohealops-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
